### ISSUE TITLE
need to define libssl to use toolbelt

### ISSUE THREAD

**Issue by naxmefy** [wercker/step-heroku-deploy#31]
Just a info

Had following errors:

```
type heroku: heroku is /usr/local/heroku/bin/heroku
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/openssl.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/heroku/lib/heroku/jsplugin.rb:124:in `setup'
	from /usr/local/heroku/lib/heroku/cli.rb:23:in `start'
	from /usr/local/heroku/bin/heroku:24:in `<main>'
heroku version: 
starting heroku run php artisan migrate -n
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/openssl.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/heroku/lib/heroku/jsplugin.rb:124:in `setup'
	from /usr/local/heroku/lib/heroku/cli.rb:23:in `start'
	from /usr/local/heroku/bin/heroku:24:in `<main>'
```

my wercker.yml:

```YAML
box: ryanwinchester/wercker-laravel5

build:
  steps:
    - script:
        name: Install dependencies
        code: |
          composer install

    - script:
        name: Create env file
        code: |-
          cp .env.example .env

    - script:
        name: Generate application key
        code: |-
          php artisan key:generate

    - script:
        name: Run phpunit
        code: |-
          vendor/bin/phpunit --coverage-text

deploy:
  steps:
    - heroku-deploy:
        keep-repository: true
        run: php artisan migrate -n

        # DO NOT FORGET TO SET HEROKU API KEY TO $HEROKU_KEY
        # DO NOT FORGET TO SET HEROKU APP NAME TO $HEROKU_APP_NAME
```

need to add following before heroku-deploy:

```YAML
- install-packages:
        packages: libssl-dev ruby
```
