### ISSUE TITLE
Raising Migration Errors

### ISSUE THREAD

**Issue by phoenixbox** [wercker/step-heroku-deploy#32]
Hey there,

below is an example of my `heroku-deploy` step.
```
deploy:
  steps:
    - heroku-deploy:
        key: #####
        key-name:#####
        user: #####
        app-name: #####
        run: rake db:migrate
  after-steps:
      - slack-notifier:
          url: #####
          channel: #####
          username: #####
          branch: #####
```

When migrations fail, an error is raised in the wercker logs but not passed to the Slack notifier, and the Wercker deploy pipeline itself passes.

Does anyone know how I can raise these errors, and be notified of them?
